# Generated by Django 4.2.3 on 2023-07-26 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_gen', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='decscription',
            new_name='description',
        ),
    ]
