# Generated by Django 4.2.3 on 2023-07-30 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_gen', '0002_rename_decscription_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Name'),
        ),
    ]
