# Generated by Django 4.2.3 on 2023-07-23 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='document',
        ),
        migrations.AddField(
            model_name='course',
            name='pdf',
            field=models.FileField(null=True, upload_to='./courses/pdfs/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='tuition',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
