# Generated by Django 4.2.3 on 2023-07-23 02:40

from django.db import migrations
from django.core.files import File
import sys

# setting path
sys.path.append('../../courses')

# importing
from courses.models import Course

def createData(apps, schema_editor):
    # Get the model from the versioned app registry
    Course = apps.get_model('courses', 'Course')
    Course(name="Intro to Python", tuition=500.00).save()
    


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_course_document_course_pdf_alter_course_name_and_more'),
    ]

    operations = [
        migrations.RunPython(createData)
    ]
